In [2]:
import pandas as pd
import numpy as np

pd.__version__

'1.3.4'

In [3]:
#solo tengamos 2 digitos despues del punto

np.set_printoptions(precision=2)

In [4]:
x1 = np.random.rand(2,5)*100
x1

array([[91.3 , 72.95, 51.35, 29.33, 55.99],
       [44.12, 78.53,  5.19, 36.38, 27.  ]])

In [5]:
x2 = np.random.rand(2,5)*100
x2

array([[57.21, 41.92,  3.73, 32.42, 70.86],
       [ 6.43, 26.52, 22.22, 85.  , 99.81]])

In [6]:
#concatenar los datafreme
np.concatenate([x1,x2])

array([[91.3 , 72.95, 51.35, 29.33, 55.99],
       [44.12, 78.53,  5.19, 36.38, 27.  ],
       [57.21, 41.92,  3.73, 32.42, 70.86],
       [ 6.43, 26.52, 22.22, 85.  , 99.81]])

In [7]:
np.concatenate([x1,x2]).shape

(4, 5)

In [8]:
s1= pd.Series(x1[0],index=["a","b","c","d","e"])
s1

a    91.300008
b    72.951931
c    51.346888
d    29.326418
e    55.988966
dtype: float64

In [9]:
s2= pd.Series(x2[0],index=["a","b","c","d","e"])
s2

a    57.207637
b    41.917337
c     3.730553
d    32.419677
e    70.861705
dtype: float64

In [10]:
s3 = pd.concat([s1,s2],axis=1)
s3

0          1
a  91.300008  57.207637
b  72.951931  41.917337
c  51.346888   3.730553
d  29.326418  32.419677
e  55.988966  70.861705

In [11]:
Dt1 = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns=["a","b","c"])
Dt1

a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [12]:
def funcion(x):
    y = x * 10
    return y

In [13]:
dt3= funcion(Dt1)
dt3

a   b   c
0  10  20  30
1  40  50  60
2  70  80  90

In [14]:
pd.concat([Dt1,dt3])

a   b   c
0   1   2   3
1   4   5   6
2   7   8   9
0  10  20  30
1  40  50  60
2  70  80  90

In [15]:
pd.concat([Dt1,dt3],axis=1)

a  b  c   a   b   c
0  1  2  3  10  20  30
1  4  5  6  40  50  60
2  7  8  9  70  80  90

In [19]:
Dt1.append(dt3)


a   b   c
0   1   2   3
1   4   5   6
2   7   8   9
0  10  20  30
1  40  50  60
2  70  80  90

In [21]:
Dt1.T

0  1  2
a  1  4  7
b  2  5  8
c  3  6  9